[server]
fileWatcherType = "poll"

[theme]
primaryColor="#8FE1A8"
backgroundColor="#151515"
secondaryBackgroundColor="#2D2D2A"
textColor="#00000"
font="sans serif"

[client]
showSidebarNavigation = false
