# fly.toml app configuration file generated for green-griddle-mysql on 2024-05-31T10:29:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'green-griddle-mysql'
primary_region = 'ams'

[build]
  image = 'mysql:8'

[env]
  DB_HOST = 'db'
  DB_NAME = 'northwind'
  DB_PORT = '3306'
  DB_USER = 'root'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
