name: Fly Deploy Api
on:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
